
// GET PRODUCT API

export const GET_PRODUCT_PROGRESS = "GET_PRODUCT_PROGRESS"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"


// UPDATE PRODUCT API

export const UPDATE_PRODUCT_PROGRESS = "UPDATE_PRODUCT_PROGRESS"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"